### ISSUE TITLE
Existing World Incompatibility

### ISSUE THREAD

**Issue by TheHaterofGravel** [GratuitousEntertainment/GEHelveHammer#2]
The mod seems to have issue with patching existing worlds, my server-event log shows the server getting spammed by this after it loads up the world, causing the world to not load and the player to be stuck in and unloaded void, until the server times out.

18.10.2020 18:50:23 [Event] Singleplayer Server now running!
18.10.2020 18:50:29 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at gehelvehammer.src.GEBlockEntityAnvil.OnHelveHammerHitPatch(BlockEntityAnvil& __instance)
   at Vintagestory.GameContent.BlockEntityAnvil.OnHelveHammerHit_Patch4(BlockEntityAnvil this)
   at Vintagestory.GameContent.Mechanics.BEHelveHammer.onEvery25ms(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Server.ServerMain.Process()
18.10.2020 18:50:29 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at gehelvehammer.src.GEBlockEntityAnvil.OnHelveHammerHitPatch(BlockEntityAnvil& __instance)
   at Vintagestory.GameContent.BlockEntityAnvil.OnHelveHammerHit_Patch4(BlockEntityAnvil this)
   at Vintagestory.GameContent.Mechanics.BEHelveHammer.onEvery25ms(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Server.ServerMain.Process()
keeps spamming this until server times out.

**Comment by GratuitousEntertainment** [comment]
Odd; its integrated perfectly into our existing servers. / games

Are you running in Linux or windows?

Is it possible you had anvils already in the process of smithing when your game world was saved?

Have you tried it on a fresh world (creative) to see if it still spams this message?

**Comment by GratuitousEntertainment** [comment]
@TheHaterofGravel   If you have a moment could you let me know if you're running any other mods that might touch smithing?  From what we've gathered this may be related to two mods trying to change the anvil behavior.
